### ISSUE TITLE
Interval.pow could be improved for special cases of negative powers.

### ISSUE THREAD

**Issue by tetslee** [maurizzzio/interval-arithmetic#14]
At the moment, `Interval.pow(Interval(0, 1), -2)` returns [-Infinity, Infinity].
`Interval.pow(Interval( Interval.round.next(0), 1), -2)` also returns [-Infinity, Infinity].

It would be more useful if these cases returned [1 - ε, Infinity] instead.

**Comment by maurizzzio** [comment]
The problem lies on the computation of the powers of 0. First, when `pow` is called with a negative power e.g. `[0, 1]^-2` it's computed doing `1 /[0, 1]^2` (see [`multiplicative-inverse`](https://maurizzzio.github.io/interval-arithmetic/0.6.8/Interval.html#multiplicativeInverse)), now to compute `[0, 1]^2` by the rounding rules it's like `[powPrev(0, 2), powNext(1, 2)]` which creates an interval which contains has negative and positive ends, since it also includes zero any division by zero creates a [`WHOLE interval`](https://maurizzzio.github.io/interval-arithmetic/0.6.8/constants.html)

To solve this I can add a simple rule in `powPrev, powNext` so that if zero is the base then the result is simply zero therefore `[powPrev(0, 2), powNext(1, 2)] = [0, next(1)]` so `1 / [0, next(1)] = [1 - ε, Infinity]` however this doesn't work for the second case unfortunately

**Comment by maurizzzio** [comment]
I've also come up with the idea of computing `1/[0, 1]^2` as `[1/0, 1/1]^2` (the ends need to be swapped for this case), I don't know if it'll work but I'll give it a try
